/*
Language: lsFusion
Author: Aliaksei Danchanka <danchenko@gmail.com>
Description: lsFusion platform programming language
*/

function(hljs) {
  var LSF_KEYWORDS = { 
    keyword  : 'INTEGER DOUBLE LONG BOOLEAN DATE DATETIME TEXT STRING ISTRING ' +
            'VARISTRING VARSTRING TIME RICHTEXT ' +
            'ABSTRACT ACTION ACTIVE ACTIVATE NEW AFTER AGGR ALL AND APPEND APPLY ' +
            'AS ASON ASYNCUPDATE ATTACH ATTR AUTO AUTOREFRESH AUTOSET BACKGROUND ' +
            'BCC BEFORE BODY BOTTOM BREAK BY CANCEL CANONICALNAME CASE CC CENTER ' +
            'CHANGE CHANGECLASS CHANGEABLE CHANGED CHANGEKEY CHANGEWYS CHARSET CHECK ' +
            'CHECKED CLASS CLIENT CLOSE COLOR COLUMNS COMPLEX CONCAT CONFIRM ' +
            'CONNECTION CONSTRAINT CONTAINERH CONTAINERV CONTEXTMENU CSV CSVFILE CSVLINK ' +
            'CUSTOM CYCLES DATA DBF DEFAULT DEFAULTCOMPARE DELAY DELETE DESC DESIGN ' +
            'DIALOG DO DOC DOCKED DOCX DRAWROOT DROP DROPCHANGED ECHO EDIT ELSE ' +
            'EMAIL END ESCAPE EQUAL EVAL EVENTID EVENTS EXCELFILE EXCELLINK ' +
            'EXCEPTLAST EXCLUSIVE EXEC EXPORT EXTEND EXTERNAL FALSE FIELDS FILE ' +
            'FILTER FILTERGROUP FILTERS FINALLY FIRST FIXED FOLDER FOOTER FOR FORCE ' +
            'FOREGROUND FORM FORMS FORMULA FROM FULL GET GOAFTER GRID GROUP ' +
            'GROUPCHANGE HALIGN HEADER HIDE HIDESCROLLBARS HIDETITLE HINTNOUPDATE ' +
            'HINTTABLE HORIZONTAL HTML HTMLFILE HTMLLINK HTTP IF IMAGE IMAGEFILE ' +
            'IMAGELINK IMPORT IMPOSSIBLE IN INDEX INDEXED INIT INITFILTER INLINE ' +
            'INTERNAL INPUT IS JAVA JOIN JSON JSONFILE JSONLINK KEYPRESS LAST ' +
            'LEFT LIKE LINK LIMIT LIST LOCAL LSF LOGGABLE MANAGESESSION MAX MEMO ' +
            'MESSAGE META MIN MODULE MOVE MS MULTI NAGGR NAME NAMESPACE NATIVE ' +
            'NAVIGATOR NESTED NEW NEWEXECUTOR NEWSESSION NEWSQL NEWTHREAD NO NOCANCEL ' +
            'NOESCAPE NOHEADER NOHINT NONULL NODEFAULT NOT NOWAIT NULL NUMERIC ' +
            'OBJECT OBJECTS OK ON OPTIMISTICASYNC OR ORDER OVERRIDE PAGESIZE PANEL ' +
            'PARENT PARTITION PASSWORD PDF PDFFILE POST RAWFILE PDFLINK RAWLINK ' +
            'PERIOD MATERIALIZED PG POSITION PREV PRINT PRIORITY PROPERTIES PROPERTY ' +
            'PROPORTION PUT QUERYOK QUERYCLOSE QUICKFILTER READ READONLY READONLYIF ' +
            'RECURSION REFLECTION REGEXP REMOVE REPORT REPORTFILES REQUEST REQUIRE ' +
            'RESOLVE RETURN RGB RIGHT ROOT ROUND RTF SCHEDULE SCROLL SEEK ' +
            'SELECTOR SESSION SET SETCHANGED SETDROPPED SHOW SHOWIF SINGLE SHEET ' +
            'SPLITH SPLITV SQL STEP STRETCH STRICT STRUCT SUBJECT SUM TAB TABBED ' +
            'TABLE TABLEFILE TABLELINK TAG TEXTHALIGN TEXTVALIGN THEN THREADS THROW ' +
            'TIME TO DRAW TOOLBAR TOP TRAILING TREE TRUE TRY UNGROUP VALIGN ' +
            'VALUE VERTICAL VIEW WHEN WHERE WHILE WINDOW WORDFILE WORDLINK WRITE ' +
            'XLS XLSX XML XMLFILE XMLLINK XOR YES'
        };


  var LSF_INT_LITERAL = '\\b\\d+[Ll]?\\b';
  var LSF_NUMERIC_LITERAL = '\\b\\d+[.]\\d*\\b';
  var LSF_DOUBLE_LITERAL = '\\b\\d+[.]\\d*[dD]\\b'; 
  var LSF_DATE_LITERAL = '\\b\\d\\d\\d\\d[_]\\d\\d[_]\\d\\d\\b';
  var LSF_DATETIME_LITERAL = '\\b\\d\\d\\d\\d[_]\\d\\d[_]\\d\\d[_]\\d\\d[:]\\d\\d\\b';
  var LSF_TIME_LITERAL = '\\b\\d\\d[:]\\d\\d\\b'; 
  var LSF_COLOR_LITERAL = '#[0-9A-Fa-f]{6}\\b';

  var LSF_INT_MODE = {
    className: 'number',
    begin: LSF_INT_LITERAL,
    relevance: 0
  };

  var LSF_NUMERIC_MODE = {
    className: 'number',
    begin: LSF_NUMERIC_LITERAL,
    relevance: 0
  }

  var LSF_DOUBLE_MODE = {
    className: 'number',
    begin: LSF_DOUBLE_LITERAL
  }

  var LSF_DATE_MODE = {
    className: 'number',
    begin: LSF_DATE_LITERAL,
    relevance: 10 
  }

  var LSF_DATETIME_MODE = {
    className: 'number',
    begin: LSF_DATETIME_LITERAL,
    relevance: 10 
  }

  var LSF_TIME_MODE = {
    className: 'number',
    begin: LSF_TIME_LITERAL,
    relevance: 10 
  }

  var LSF_COLOR_MODE = {
    className: 'number',
    begin: LSF_COLOR_LITERAL,
  } 

  var LSF_META_CONCAT_OPERATOR_MODE = {
    className: 'meta',
    begin: '###?' 
  } 

  var LSF_META_CALL = {
    className: 'meta',
    begin: '@\\w+([.]\\w+)?\\s*',
    end: '\\(',
    excludeEnd: true
  } 

  return {
    case_incensitive: false,
    aliases: ['lsf'],
    keywords: LSF_KEYWORDS,
    illegal: '</',
    contains: [
      hljs.C_LINE_COMMENT_MODE,
      hljs.APOS_STRING_MODE,
      LSF_DATETIME_MODE,
      LSF_DATE_MODE,
      LSF_TIME_MODE,
      LSF_DOUBLE_MODE,
      LSF_NUMERIC_MODE,
      LSF_INT_MODE,
      LSF_COLOR_MODE, 
      LSF_META_CONCAT_OPERATOR_MODE,
      LSF_META_CALL
    ]
  };
}
